public class exception{
public static void main(String[] args){
ArithmeticException =new ArithmeticException(e);

try{
throw e;
}
catch(ArithmeticException p){
System.out.println("exception caught");
}
}
}
